version: '3'
services:
  app:
    build: .
    #  ./srcディレクトリをコンテナ内の/appディレクトリにマウント
    volumes:
      - ./src:/app
    # Node.jsのファイル監視機能→ファイルの変更を自動的に検知する
    environment:
      - WATCHPACK_POLLING=true
    # コンテナが起動したときに実行されるコマンド
    command: sh -c "npm run dev"
    # ポートのマッピング(Host:Port)
    ports:
      - "3000:3000"
