version: '3'
services:
  app:
    build: .
    #  コンテナにマウントするディレクトリを指定
    volumes:
      - ./src:/app
      - node_modules:/app/node_modules
      - ./src/next:/app/.next
    # Node.jsのファイル監視機能→ファイルの変更を自動的に検知する
    environment:
      - WATCHPACK_POLLING=true
    # コンテナが起動したときに実行されるコマンド
    command: sh -c "npm run dev"
    # ポートのマッピング(Host:Port)
    ports:
      - "3000:3000"
volumes:
  node_modules:
  next: